framework:
    messenger:
        buses:
            boutdecode_etl_core.command.bus:
                default_middleware: allow_no_handlers
            boutdecode_etl_core.query.bus: ~

        routing:
            'BoutDeCode\ETLCoreBundle\CQS\Application\Operation\Query\SyncQuery': sync
            'BoutDeCode\ETLCoreBundle\CQS\Application\Operation\Command\SyncCommand': sync
            'BoutDeCode\ETLCoreBundle\CQS\Application\Operation\Command\AsyncCommand': async
            'BoutDeCode\ETLCoreBundle\CQS\Application\Operation\Query\AsyncQuery': async
