framework:
    workflows:
        pipeline_lifecycle:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'statusValue'
            supports:
                - BoutDeCode\ETLCoreBundle\Core\Domain\Model\Pipeline
            initial_marking: pending
            places:
                - pending
                - scheduled
                - in_progress
                - completed
                - failed
            transitions:
                schedule:
                    from: pending
                    to: scheduled
                start:
                    from: scheduled
                    to: in_progress
                complete:
                    from: in_progress
                    to: completed
                fail:
                    from: in_progress
                    to: failed
                reset:
                    from: [scheduled, completed, failed]
                    to: pending
                restart:
                    from: failed
                    to: in_progress
